# DevSpace configuration for ark-apiserver service
version: v2beta1

images:
  ark-apiserver:
    image: ark-apiserver
    dockerfile: ./Dockerfile
    context: .

pipelines:
  deploy: |-
    build_images --all
    create_deployments --all
  dev: |-
    create_deployments --all
    start_dev --all

commands:
  copy-db:
    description: Copy SQLite database from pod to ./ark.db
    command: |
      POD=$(kubectl get pod -n ark-system -l app.kubernetes.io/name=ark-apiserver -o jsonpath='{.items[0].metadata.name}')
      kubectl cp ark-system/$POD:/data/ark.db ./ark.db
      echo "Copied to ./ark.db"

deployments:
  ark-apiserver:
    namespace: ark-system
    helm:
      chart:
        path: ./chart
      values:
        image:
          repository: ${runtime.images.ark-apiserver.image}
          tag: ${runtime.images.ark-apiserver.tag}
        storage:
          driver: sqlite
          sqlite:
            persistence:
              enabled: false
        # Higher limits for Go compilation during development
        resources:
          limits:
            memory: "2048Mi"
            cpu: "2000m"
          requests:
            memory: "256Mi"
            cpu: "200m"
        podSecurityContext:
          fsGroup: 0
        securityContext:
          runAsNonRoot: false
          runAsUser: 0

dev:
  ark-apiserver:
    imageSelector: ark-apiserver
    devImage: golang:1.24.11-bookworm
    command: ["sh", "-c", "cd /app && GOTOOLCHAIN=auto go run cmd/apiserver/main.go --secure-port=8443 --storage-driver=sqlite --sqlite-path=/data/ark.db"]
    namespace: ark-system
    logs:
      lastLines: 50
    sync:
      - path: .:/app
        startContainer: true
        disableDownload: true
        uploadExcludeFile: .dockerignore
        onUpload:
          restartContainer: true
    ssh:
      enabled: true
