version: v2beta1

vars:
  HTTPROUTE_ENABLED:
    command: |-
      if kubectl get crd httproutes.gateway.networking.k8s.io >/dev/null 2>&1; then
        echo "true"
      else
        echo "false"
      fi

pipelines:
  dev: |-
    create_deployments --all

deployments:
  clickhouse:
    namespace: clickhouse
    helm:
      chart:
        path: ./chart
      values:
        httpRoute:
          enabled: ${HTTPROUTE_ENABLED}

hooks:
  - command: |-
      if kubectl get crd httproutes.gateway.networking.k8s.io >/dev/null 2>&1; then
        echo "✓ Gateway API HTTPRoute CRD found - HTTPRoute will be created"
      else
        echo "✗ Gateway API HTTPRoute CRD not found - HTTPRoute will be skipped"
      fi
    events: ["before:deploy:clickhouse"]
  - command: |-
      echo ""
      echo "ClickHouse deployed successfully!"
      echo "HTTP API: http://clickhouse-svc.clickhouse.127.0.0.1.nip.io:8080"
      echo "Port-forward HTTP: kubectl port-forward -n clickhouse svc/clickhouse-svc 8123:8123"
      echo "Port-forward Native: kubectl port-forward -n clickhouse svc/clickhouse-svc 9000:9000"
      echo ""
      echo "Test connection:"
      echo "  kubectl run -it --rm clickhouse-client --image=clickhouse/clickhouse-client --restart=Never -- clickhouse-client --host clickhouse-svc.clickhouse.svc.cluster.local"
    events: ["after:deploy:clickhouse"]
