# Round Robin Team with System Message Hydration and Termination
# This example demonstrates:
# 1. A team with round-robin strategy
# 2. An agent that includes its system message in memory storage
# 3. An agent that can terminate conversations
# 4. Memory integration for conversation context

# Agent with system message in its prompt
# System messages are always stored in memory automatically.
# Whether they are hydrated (loaded back) is controlled by the Query annotation.
apiVersion: ark.mckinsey.com/v1alpha1
kind: Agent
metadata:
  name: agent-rr-with-system-messages
spec:
  prompt: Append "Bazinga!" to the user input and say it. Count how many times "Bazinga" appears in the conversation history. If you see "Bazinga" mentioned 3 or more times total (including your own responses), call the terminate tool to end the conversation.
  tools:
    - type: built-in
      name: terminate
---
apiVersion: ark.mckinsey.com/v1alpha1
kind: Team
metadata:
  name: team-rr-with-system-messages
spec:
  members:
    - name: agent-rr-with-system-messages
      type: agent
  strategy: "round-robin"
  maxTurns: 10
---
apiVersion: ark.mckinsey.com/v1alpha1
kind: Query
metadata:
  name: query-rr-with-system-messages
  annotations:
    # This annotation tells ARK to include system messages from memory
    ark.mckinsey.com/memory-hydrate-system-message: "true"
spec:
  input: "Sheldon says:"
  memory:
    name: default
  targets:
    - type: team
      name: team-rr-with-system-messages
