# DevSpace configuration for Phoenix observability
version: v2beta1

pipelines:
  dev: |-
    create_deployments --all
    
    echo ""
    echo "Phoenix Dashboard: http://localhost:6006"
    echo "Press Ctrl+C to stop port-forwarding"
    echo ""
    
    # Wait for Phoenix to be ready and start port-forwarding
    echo "Waiting for Phoenix to be ready..."
    until kubectl port-forward -n phoenix svc/phoenix-svc 6006:6006; do 
      echo "Port-forwarding failed - Phoenix not ready yet. Retrying in 10s..."
      sleep 10
    done

deployments:
  phoenix:
    namespace: phoenix
    helm:
      chart:
        path: ./chart
      values:
        # Development-specific values can be added here
        httpRoute:
          # when true, http://phoenix.phoenix.127.0.0.1.nip.io:8080 will be created
          enabled: false
        otelEnvironmentVariableSecrets:
          enabled: true
          namespaces:
            - ark-system
            - default
